### ISSUE TITLE
Expand object not using value.

### ISSUE THREAD

**Issue by uriafranko** [merge-api/merge-python-client#60]
When using the Expand enum it sends to the URL the written name of the object
OpportunitiesListRequestExpand.STAGE
instead of just "stage"

**Comment by dsinghvi** [comment]
@helgi-empower this should be fixed in the latest SDK! If you're still running into an issue let us know. For context, Merge uses [Fern](https://buildwithfern.com/) to generate SDKs and you can see this [changelog](https://github.com/fern-api/fern/blob/main/generators/python/sdk/CHANGELOG.md#0102---2024-02-18) where the bug was fixed in our Python generator.
